### ISSUE TITLE
Breaking loops in PsychoJS

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#68]
Loops can be broken using either `<loop>.finished = true;` or `currentLoop.finished = true;`. In a task with nested loops, breaking loop behaviour differs between PsychoPy and PsychoJS. In PsychoPy, the break loop commands only break the current iteration of the inner loop and allow the inner loop to continue for the nReps of the outer loop. In PsychoJS, breaking the inner loop also breaks the outer loops. In the example below, we attempt to break the sequential numbers (1 to 5) being presented in the inner loop when the sequential numbers == 2. In PsychoPy, this results in the numbers 1 and 2 being presented 5 times (the nReps of the outer loop). In PsychoJS, the experiment ends after only a single presentation of the inner loop. 

https://run.pavlovia.org/dvbridges/breakingloops/html/

**Comment by dvbridges** [comment]
Fixed. For example, to end a loop, use the following to end the loop when on the 2nd repetition of that current loop:

```
if (currentLoop.thisRepN == 2) 
  {
    trials.finished = true;
  }
```

**Comment by joaquinmoris** [comment]
Hi,
I've just checked this task, using the link provided. It does not stop until the end of the task, the line trials.finished = true; does not end the loop.
I get the same behaviour in Edge, Firefox, Chrome and Brave (Windows 10).

**Comment by gcristoforetti** [comment]
Hi, I am trying to implement the code above for my experiment. I want to end an inner loop (counting) after 10 sec without breaking the outer loop.  Did anyone had a similar problem? Thanks in advance!
 
This is my js code which works in builder. 

In the routine before the inner loop 
Begin Routine
totalTime = 0;
timeLimit = 10;
incrementalClock = new util.Clock();

in the inner loop

Begin routine
incrementalClock.reset()

EachFrame
if (((totalTime + incrementalClock.getTime())) >= timeLimit) 
    {
    counting.finished=true;
    continueRoutine =false;  
    }

EndRoutine
totalTime+=incrementalClock.getTime()

**Comment by dvbridges** [comment]
@joaquinmoris , thanks, I checked and have a working version demonstrating that the code to break loops is working correctly. The inner loop is set up to break on the second (out of 5) trials, for 2 nReps of the outer loop:

https://run.pavlovia.org/dvbridges/test_breakloop/html/

There is an issue with auto-translate here, which used the name of the actual loop, rather than the generic name "trials". @gcristoforetti , perhaps this is your issue, since your code shows you are using the loop name, rather than "trials". The [Discourse forum](https://discourse.psychopy.org/) is the best place for coding issues.

**Comment by reblando** [comment]
Hi, I am still having issues breaking out of a loop with trial.finished = true; 
For more context 
`if (key_resp_25.keys == 2) {
    trials.finished = true;
    continueRoutine = false;
    }`

(The loop name is called 'trials')

The loop keeps going even when the condition is met. Please help!

**Comment by xf15** [comment]
is there is a solution for this yet?
